$background = 020304
$onBackground = e0e6ee
$surface = 020304
$surfaceDim = 020304
$surfaceBright = 090d11
$surfaceContainerLowest = 000000
$surfaceContainerLow = 030507
$surfaceContainer = 04070a
$surfaceContainerHigh = 06090c
$surfaceContainerHighest = 080b0f
$onSurface = e0e6ee
$surfaceVariant = 080b0f
$onSurfaceVariant = a5acb3
$outline = 70767d
$outlineVariant = 42494f
$inverseSurface = f8f9fd
$inverseOnSurface = 525559
$shadow = 000000
$scrim = 000000
$surfaceTint = 1d2933
$primary = a9cae8
$primaryDim = 9bbdda
$onPrimary = 21435c
$primaryContainer = 35566f
$onPrimaryContainer = cce6ff
$inversePrimary = 42627c
$primaryFixed = badbfa
$primaryFixedDim = accdeb
$onPrimaryFixed = 183b53
$onPrimaryFixedVariant = 375871
$secondary = b8c8d9
$secondaryDim = aabbcb
$onSecondary = 32424f
$secondaryContainer = 2d3d4b
$onSecondaryContainer = b0c1d2
$secondaryFixed = d4e4f6
$secondaryFixedDim = c6d6e7
$onSecondaryFixed = 31414f
$onSecondaryFixedVariant = 4d5d6c
$tertiary = ddddff
$tertiaryDim = cdcefe
$onTertiary = 4b4d75
$tertiaryContainer = cdcefe
$onTertiaryContainer = 42446c
$tertiaryFixed = cdcefe
$tertiaryFixedDim = bfc0ef
$onTertiaryFixed = 2f3157
$onTertiaryFixedVariant = 4b4d75
$error = fa746f
$errorDim = c54d4a
$onError = 490006
$errorContainer = 871f21
$onErrorContainer = ff9993
$primaryPaletteKeyColor = 5a7b96
$secondaryPaletteKeyColor = 697988
$tertiaryPaletteKeyColor = 72739e
$neutralPaletteKeyColor = 75777b
$neutralVariantPaletteKeyColor = 71787f
$errorPaletteKeyColor = c84f4c
$primary_paletteKeyColor = 5a7b96
$secondary_paletteKeyColor = 697988
$tertiary_paletteKeyColor = 72739e
$neutral_paletteKeyColor = 75777b
$neutral_variant_paletteKeyColor = 71787f
$term0 = 080808
$term1 = 8383ff
$term2 = 44def5
$term3 = 75fcdd
$term4 = 81b0cd
$term5 = 89aaed
$term6 = 89d3f0
$term7 = ccdcd6
$term8 = 9aa59f
$term9 = a29eff
$term10 = 89ecff
$term11 = c9fff3
$term12 = a8c5d5
$term13 = a7bef8
$term14 = a0e5ff
$term15 = ffffff
$rosewater = f4f0fa
$flamingo = dfe0f5
$pink = cdddff
$mauve = 96c3ff
$red = 91b3ff
$maroon = abbef0
$peach = e0c2f9
$yellow = d0f9f4
$green = b0e8ff
$teal = bae6ff
$sky = b5e1ff
$sapphire = 8acfff
$blue = 7fc3fe
$lavender = a6d1ff
$klink = 398ec6
$klinkSelection = 378ec6
$kvisited = 3882d9
$kvisitedSelection = 3482d8
$knegative = 607eff
$knegativeSelection = 607eff
$kneutral = c794ff
$kneutralSelection = c794ff
$kpositive = 00b7e5
$kpositiveSelection = 00b8e4
$text = e0e6ee
$subtext1 = a5acb3
$subtext0 = 70767d
$overlay2 = 191919
$overlay1 = 161616
$overlay0 = 131313
$surface2 = 0e0f11
$surface1 = 0a0b0c
$surface0 = 030406
$base = 000001
$mantle = 000001
$crust = 000001
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
